### ISSUE TITLE
0.28.0 broken on macOS

### ISSUE THREAD

**Issue by virtualritz** [sebcrozet/kiss3d#257]
```
   Compiling kiss3d v0.28.0
error[E0432]: unresolved import `glutin::platform::unix`
  --> /Users/moritz/.cargo/registry/src/github.com-1ecc6299db9ec823/kiss3d-0.28.0/src/window/gl_canvas.rs:40:35
   |
40 |             use glutin::platform::unix::EventLoopExtUnix;
   |                                   ^^^^ could not find `unix` in `platform`

error[E0599]: no function or associated item named `new_any_thread` found for struct `EventLoop<_>` in the current scope
  --> /Users/moritz/.cargo/registry/src/github.com-1ecc6299db9ec823/kiss3d-0.28.0/src/window/gl_canvas.rs:41:24
   |
41 |             EventLoop::new_any_thread()
   |                        ^^^^^^^^^^^^^^ function or associated item not found in `EventLoop<_>`

error[E0308]: mismatched types
  --> /Users/moritz/.cargo/registry/src/github.com-1ecc6299db9ec823/kiss3d-0.28.0/src/window/gl_canvas.rs:79:13
   |
79 |             events,
   |             ^^^^^^ expected struct `EventLoop`, found struct `EventLoopWindowTarget`
   |
   = note: expected struct `EventLoop<()>`
              found struct `EventLoopWindowTarget<_>`

error: aborting due to 3 previous errors
```

**Comment by ThomAub** [comment]
Hello, 
I have the same issue as you but it might be due to some changes in `glutin` ?

**Comment by alvinhochun** [comment]
This is a regression from #253.

@jerry73204 Would you like to take a look at fixing this? Probably just some incorrect `cfg` attributes.

**Comment by jerry73204** [comment]
I pushed #259. Please check if that fix works for you.

**Comment by ThomAub** [comment]
should i close my PR #258 in favor of #259 ?

**Comment by jerry73204** [comment]
I missed #258. The only subtle difference is `#[cfg(windows)]` and ` #[cfg(any(target_os = "windows"))]`. I respect your earlier work and close #259.

**Comment by ThomAub** [comment]
That's why i proposed to take yours instead IMHO it was better handle.  
Good thing it's working now on macOS :)

**Comment by virtualritz** [comment]
Confirmed, master builds & works fine on macOS now.
